import type { Metadata } from "next";
import { JetBrains_Mono, Libre_Baskerville } from "next/font/google";
import "./globals.css";

const libreBaskervilleSans = Libre_Baskerville({
  weight: "400",
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libreBaskervilleSans.variable} ${jetBrainsMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
